# -*- coding: utf-8 -*-
"""Nyoba_selenium

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Qw51E4thbiKoM-CE8TK1ZYyJ0QpvQsII
"""

pip install selenium

pip install selenium webdriver-manager

!apt update
!apt install chromium-chromedriver
!cp /usr/lib/chromium-browser/chromedriver /usr/bin

from selenium import webdriver
from selenium.webdriver.chrome.options import Options
from selenium.webdriver.common.by import By
from selenium.webdriver.common.keys import Keys
import time

# Setup headless Chromium
options = Options()
options.add_argument('--headless')
options.add_argument('--disable-dev-shm-usage')
options.add_argument('--no-sandbox')
options.binary_location = '/usr/bin/chromium-browser'

driver = webdriver.Chrome(options=options)

# Buka Google dan cari
driver.get("https://www.google.com")
time.sleep(2)

search_box = driver.find_element(By.NAME, "q")
search_box.send_keys("Bagaimana agar kita dapat bertahan hidup dihutan?")
search_box.send_keys(Keys.RETURN)

time.sleep(2)
print("Judul halaman:", driver.title)

driver.quit()

""""Di sini saya menggunakan Selenium di Google Colab dengan browser Chromium headless. Karena Colab gak punya Chrome GUI, jadi kita install Chromium dan Chromedriver dulu, lalu otomatis jalankan pencarian Google dan ambil hasilnya."

Penjelasan Kode Selenium untuk Mencari di Google (Rekaman Presentasi)
Import Library Selenium
Kita mulai dengan mengimpor modul dari Selenium, seperti webdriver untuk mengendalikan browser, Options untuk mengatur konfigurasi browser, By dan Keys untuk mencari elemen dan simulasi keyboard.

Konfigurasi Browser Headless
Kita setup browser Chrome agar berjalan dalam mode headless, artinya tanpa tampilan jendela browser yang muncul. Ini berguna untuk menjalankan script otomatis tanpa gangguan GUI.
--disable-dev-shm-usage dan --no-sandbox adalah opsi tambahan agar Chrome berjalan lancar di lingkungan server atau container seperti Google Colab.

Membuka Halaman Google
Menggunakan perintah driver.get() kita membuka halaman utama Google.

Menunggu Halaman Siap
Fungsi time.sleep(2) memberi jeda 2 detik supaya halaman benar-benar termuat sebelum mencari elemen.

Menemukan Kotak Pencarian
driver.find_element(By.NAME, "q") digunakan untuk menemukan elemen input dengan nama "q", yaitu kotak pencarian Google.

Mengisi dan Mengirim Kata Kunci Pencarian
Dengan send_keys("Apa itu nasi?") kita mengetik pertanyaan di kotak pencarian, lalu send_keys(Keys.RETURN) mensimulasikan tekan tombol Enter untuk memulai pencarian.

Menunggu Hasil Muncul
Lagi, kita beri jeda 2 detik agar hasil pencarian termuat.

Menampilkan Judul Halaman Hasil Pencarian
print("Judul halaman:", driver.title) menampilkan judul tab browser yang sudah berubah sesuai hasil pencarian, contohnya “Apa itu nasi? - Google Search”.

Menutup Browser
Akhirnya, driver.quit() menutup browser dan membersihkan sesi agar tidak ada proses Chrome yang berjalan di belakang layar.
"""
bacod
